### ISSUE TITLE
Will it Fix this White Boot ?

### ISSUE THREAD

**Issue by soaresden** [mupfelofen-de/WSODFix#3]
Hi and thanks to resolve this issue that some users have for past 20 years !
I saw your project and remember mine.

Here's my actual issue:
video : https://streamable.com/kxsjqn 

I tried to switch on and got this white screen boot.

I figure out a thing : 
* When I push the On button, the screen got scanlines and disappear. And then show the whitescreen
* Randomly when I discharge entirely the energy of the ngage (pushing on for 20seconds without battery) and try to switch on with the battery, it get a successfull boot.
* The green key combo doesn't work (can't remember my firmware version)

What's your point of view ?
Many Thanks

**Comment by soaresden** [comment]
answered on reddit

**Comment by mupfdev** [comment]
Context for later reference: the key combination that can be held at boot to format the user area is only available on the latest QD firmware 4.60. This version is, as far as I know, a brand-labeled firmware by a Spanish service provider.
